### ISSUE TITLE
Taskbar have bug after used.

### ISSUE THREAD

**Issue by ForGx3** [EndlessLuck/Aero-Peek-Fix#1]
That is good fix, but taskbar have bug fter use.

Window will always be above Taskbar.
The default is behind the Taskbar.

Thank you :)

![Aero Peek bug](https://github.com/EndlessLuck/Aero-Peek-Fix/assets/52027453/d8bf5ca7-d5b3-415a-be9c-6e1197574d24)

**Comment by EndlessLuck** [comment]
This should be fixed in the latest update.
https://github.com/EndlessLuck/Aero-Peek-Fix/releases/tag/1.0.3
